fix qq support
merge sormort/you-get

写错了type...

[qq] fix #548, close #443

merge sormort's you-get

Fix zhanqi

Zhanqi extractor works again...
And added ts merging implementation...

Signed-off-by: liushuyu <liushuyu_011@163.com>

Fix zhanqi again

Modified against the latest update of zhanqi's server...

Signed-off-by: liushuyu <liushuyu_011@163.com>

[Zhanqi]Modified something...

Changed something according to @jackyzy823

Update zhanqi.py

Minor fix

Fix zhanqi

Indentation fix

iqiyi new key,how it works in comment.

more reasonable tm value

sometimes there's some parameters,drop it

[Tumblr] fix for videos with no title

[Google+] fix for non-ASCII custom URLs

fix iqiyi(20150703)

[iqiyi] update: 20150710 (close #569)

[iqiyi] extract tvid & videoid from URL

version 0.3.34

Update salt.

[soundcloud] fix #575

support for python -m you_get

This makes develop-then-test easier and straghtforward

[netease] support for mv urls

example url: http://music.163.com/#/mv?id=440007

[youtube] switch to https (close #564)

[netease] support for 163.fm short url

e.g. http://163.fm/LzbHaQN

update key for iqiyi,thanks to @Freshman585

[iqiyi] new enckey

[iqiyi] new src

[iqiyi] update key

fix #582

 [iqiyi] fix 1080p parse by set um=1

Add support for Qianmo

http://qianmo.com/

Tested on my machine.

Try adding Funshion(fun.tv) support, fix #215

I have made those functions to allow full drama download, but do not
know how to integrate with the programme.

Please offer your help. Many thanks.

Revert "Try adding Funshion(fun.tv) support, fix #215"

This reverts commit c39927e9311bff1ade7c27399d09bd8d6b8b3cab.

fix iqiyi(20150820)

fix duplicate url bug for bilibili

Add Weibo Miaopai support

fix bug in tudou, fix #612

fix dailymotion for #609

Fix problems with videos that do not have 720p mode

[dailymotion] fix title

Add funshion support, fix #215, replace #601, #604

Update cntv.py

Update cntv.py

support embed player for youku/tudou

try sites one by one, to search video.
but not in video order.

Signed-off-by: Zhang Ning <zhangn1985@gmail.com>

support multi video in one page

add matchall api

matchall: almost same as match1, but it will return a list
of all matches.

[yinyuetai] switch to JSON API, close #559

rewrit iqiyi using VideoExtractor class

Signed-off-by: Zhang Ning <zhangn1985@gmail.com>

Add metacafe support

Add iQilu support

Add Vimeo Channel support

Fix #634 L2

[common] divide the import of extractors into multiple lines

[youku] support multi-page playlists

[common] fix skipping download of file existence in some cases

[IQIYI] 2015/09/18 new salt,describe method in comments of iqiyi.py

[youku] gracefully handle single failure

merge sormort's you-get

let KeyboardInterrupt bypass

[qq] reimplement qq.py, close #657

merge sormort's you-get

[755] new site support

update README.md

update .travis.yml (add 3.5 and nightly)

version 0.3.35

update you-get.json

update Makefile & setup.py

[common] fix infinite redirecting

[archive] new site support

update README.md

[iqiyi] Update enc and authkey

 [iqiyi] simplify mix() function

 add --json option: output video information in json text

 fix extractors not use VideoExtractor after add --json option

[ffmpeg] use subprocess.check_call

This fixes RuntimeError: No active exception to reraise

 --json option now can support more extractors not using VideoExtractor

[soundcloud] update client_id, fix #679

[acfun] fix "unexpected keyword argument 'json_output'"

Revert "update Makefile & setup.py" (fix #685)

This reverts commit c3ac87a7a1c5f47aa4d4dc0c1d168a8f39840ea6.

version 0.3.36

[sina] match vid from the page

fix for http://video.sina.com.cn/view/249851143.html

[iqiyi] update key (close #693)

[flickr] new site support

[mixcloud] fix

[tudou] fix playlists

Revert "fix duplicate url bug for bilibili"

[bilibili] do not download danmaku for dry_run

[bilibili] fix support of partitions (close #688)
- Download only one partition by default
- Support playlist (for downloading all partitions without merging)

Add suntv support

Fix douyu

Took @yan12125 's advice, and thanks to @yan12125 .
This fix closes #580

[common] --cookies loads Mozilla cookies.sqlite instead of Netscape cookies.txt

[bilibili] load cookies

[bilibili] clean-up

[common] support both cookies.txt and cookies.sqlite

[common] if it's not moz_cookies, pass

[common] update help message

update README.md

[bilibili] do not use description as title

update README.md

[ffmpeg] implement ffmpeg_concat_av()

[ffmpeg] set "-loglevel quiet" to suppress verbose FFmpeg output

[common] download_urls: support A/V merge using ffmpeg_concat_av()

[extractor] support dash_streams

[youtube] support dashmpd

[youtube] always parse video page (for DASH)

[travis] add webhooks for gitter integration

add *.srt to .gitignore

[common] update download_urls_chunked()

[extractor] support caption_tracks

[youtube] support caption_tracks

[common] beautify progress bar

[baomihua] fix #501

[yinyuetai] fix for mobile URL m.yinyuetai.com (#648)

[yinyuetai] support playlist

[yinyuetai] add yinyuetai_download_playlist

[bandcamp] new site support

update README.md

[heavymusic] new site support

update README.md

[netease] add netease_lyric_download()

[youtube] support DASH streams for VEVO videos

[youtube] fix AttributeError: 'YouTube' object has no attribute 'js'

[common] use importlib to import modules from dict SITES

[embed] remove duplicated embedded URLs

[universal] universal extractor and direct downloader

[youtube] set html5player when parsing video page for DASH

[common] show download speed on progress bar
- Close #178 (also requested in #284 and #700)
- Close #305

[extractor] fix #713

[common] set the proper width of progress bar

[common] oops

[netease] download lyrics for albums and playlists

[netease] let's pretend we're not using the freakin key
- http://www.v2ex.com/t/131959

[common] add handy get_head(url)

[baidu] support tieba videos and images

[common] "Video Site" -> "Site"

[vimeo] fix #718

[tumblr] download photo / photoset

[instagram] download the image

[twitter] download images

[flickr] download images

[google] download the image

[baidu] support tieba albums

[common] adjust progress bar (shorten display of speed)

[rtmpdump]

[755] download images

[common] print_info: more MIME types

[common] url_info: more MIME types

[universal] download images

[w56] partly solved #720

[vimeo] fix unescape_html(None)

[miomio] quick fix #716

[embed] add more patterns for Tudou
- Example link: http://tieba.baidu.com/p/4114753102

[common] add google_search()

[util.log] update

[you-get] update

redefine version (0.4.x)

[embed] add more patterns for Tudou
- Example link: http://tieba.baidu.com/shipin/bw/video/play?kw=akb48&v_id=a35619448853a42b942231e1

[common] improve error message, display a brief instruction to tell users what to do

[common] add new option: --output-filename (close #425)

Add Yixia-Miaopai support, replace #639

Add Pixnet support, fix #129, replace #633

[youtube] fix VEVO when no 's' field presents

[youku] support show_page, fix #726

[common] update google_search(), fix #727

remove CONTRIBUTING.md, because no one cares

update you-get.json

[universal] improve (more image patterns)

[extractor]

Add Veoh support, fix #79

[veoh] set info_only=info_only

[iqiyi] fix #728

[youtube] show error message when a video is unavailable
- As requested in #720#issuecomment-150197734

[term] fcntl module only available on Unix

Remove support:
* Blip.tv <http://blip.tv>
* Catfun (喵星球) <http://www.catfun.tv>
* Coursera <https://www.coursera.org>
* SongTaste <http://www.songtaste.com>
* VID48 <http://vid48.com>
* VideoBam <http://videobam.com>

See #732 for details.

update LICENSE.txt

Add Interest.me (CJ E&M)  support

Update Readme as #732

[common] option -d is short for --debug

rewrite README.md

update .gitignore

add a separate README.rst

version 0.4.111

[universal] catch jpeg

[util.git] fix get_version()

added new key

[universal] catch links with href to .png and .gif

[google] support URL with "?cfem=1" postfix

[universal] use filename if len(filename) >= 5

[dilidili] Add support

[universal] fix long filenames

added ternary condition on instagram extractor

[tumblr] filter out some non-image urls

version 0.4.125

[netease] fix #743

[youtube] fix #749

[youtube] enable all DASH streams

add referer to fake_headers

[iqiyi] update key (close #750)

[youtube] fix more (follow-up to 5dd7b5f)

[youtube] nope

version 0.4.134

[common] fix division by zero

version 0.4.136

update README.md

[vine] support card URLs

[twitter] support embedded Vine

[netease] switch to m5.music.126.net (as suggested in #743)

[pinterest] new site support (using VideoExtractor)

update README.md

[755] use movieUrlHq

[755] filenames may be duplicated (sometimes)

[acfun] fix #745

[embed] support embedded yinyuetai patterns

[embed] support embedded iqiyi patterns

[youtube] fix #757

[tumblr] support direct URLs

[musicplayon] new site support (using VideoExtractor)

update README.md

[google] fix for notification links

setup.py: set zip_safe to True (close #759)

[vimeo] fix

version 0.4.156

you-get: neat way to get _filepath (close #762)

[twitter] minor fix

add pattern for url like http://tv.cntv.cn/video/VSET100241824133/ee5ed807346c4b6086f105ef10b559f3

[vimeo] fix (for videos not shown public)

[iqiyi] get curid from URL (close #766)

[embed] redundant regex

[youtube] make use of browse_ajax (fix #746)

[common] do not take SystemExit wrongly

[cntv] merge=False (ffmpeg concat demuxer fails on corrupted segments, see #767)

version 0.4.167

[vimeo] support https in URL pattern (a potential improvement for all extractors in the future)

[baidu] support direct URLs (imgsrc.baidu.com)

[letv] fix #770

[sohu] fix #769

[youku] fix #771

merge soimort's you-get

[youku] print error message

merge

[youku] add support for audio languages, fix #369 (again)

merge

[youku] handle password-protected videos, fix #73 (again)

merge

version 0.4.176

[twitter] fix video extracting

[56] the actual hd type is "wvga", close #775

delete tmp.txt

merge